---
title: "Assignments"
slug: assignments
---

# Preparation

<span class="newthought">You will get the most out of this class</span> if you (1) attend class, (2) complete all the readings, and (3) engage^[Take detailed notes, do practice exercises, ask for help on the Slack]  with the readings.


# Homework

<span class="newthought">To practice coding in R</span> you will complete 7 problem sets. You need to show that you made a good faith effort to work each question. The problem sets will be graded using a check system:

- ✔+: ^[{-} *110% in gradebook*] Problem set is 100% completed. Every question was attempted and answered, and most answers are correct. Work is exceptional. I will not assign these often.
- ✔: ^[{-} *100% in gradebook*] Problem set is 70–99% complete and most answers are correct. This is the expected level of performance.
- ✔−: ^[{-} *50% in gradebook*] Problem set is less than 70% complete and/or most answers are incorrect. This indicates that you need to improve next time. I will hopefully not asisgn these often.

You may (and should!) work together on the problem sets, but *you must turn in your own answers.* You cannot work in groups of more than **three** people, and you must note who participated in the group in your assignment.



# Exams

<span class="newthought">There will be two exams</span> covering (1) the first half of the course, especially programming, and (2) the second half of the course, especially causation.

More details to come.


# Code-thru

<span class="newthought">At the end of the course,</span> you will complete a code-through project. 

More details to come.

