---
title: "Visualizing data"
citeproc: true
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-fullnote-bibliography-no-bib.csl
menu: 
  readings:
    parent: Readings
    weight: 2
type: docs
output:
  blogdown::html_page:
    toc: true
editor_options: 
  chunk_output_type: console
---


## Recommended

- <i class="fas fa-book"></i> [Ch.2 in ModernDive on Data Visualization](https://moderndive.com)

- <i class="fas fa-book"></i> [Ch.3 in R for Data Science](https://r4ds.had.co.nz/data-visualisation.html)



## Helpful!

- <i class="fa fa-external-link-square-alt" aria-hidden="true"></i> The [cheatsheet for data visualization with ggplot](https://www.rstudio.com/resources/cheatsheets/) might be a helpful resource


## Slides


**Tip**: You can navigate through the slides with <kbd>←</kbd> and <kbd>→</kbd>. If you type <kbd>F</kbd> you can go full-screen. 

### Tuesday

[Class slides here](/slides/02-viz.html)


```{r,echo=FALSE}
xaringanExtra::embed_xaringan(
   url = "/slides/02-viz.html",
   ratio = "16:9"
)
```




### Thursday

[Class slides here](/slides/03-viz2.html)


```{r,echo=FALSE}
xaringanExtra::embed_xaringan(
   url = "/slides/03-viz2.html",
   ratio = "16:9"
)
```

