---
title: "Wrangling data"
citeproc: true
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-fullnote-bibliography-no-bib.csl
menu: 
  readings:
    parent: Readings
    weight: 2
type: docs
output:
  blogdown::html_page:
    toc: true
editor_options: 
  chunk_output_type: console
---


## Recommended

- <i class="fas fa-book"></i> [Ch. 3 in ModernDive](https://moderndive.com/)
- <i class="fas fa-book"></i> [Ch. 5 in R for Data Science](https://r4ds.had.co.nz/transform.html)


## Recommended

- Print out this [cheat sheet](https://github.com/rstudio/cheatsheets/blob/master/data-transformation.pdf) and have it somewhere handy while you're doing work in this course


## Slides


**Tip**: You can navigate through the slides with <kbd>←</kbd> and <kbd>→</kbd>. If you type <kbd>F</kbd> you can go full-screen.


### Tuesday

[Class slides here](/slides/04-wrangle1.html)


```{r,echo=FALSE}
xaringanExtra::embed_xaringan(
   url = "/slides/04-wrangle1.html",
   ratio = "16:9"
)
```

### Thursday

[Class slides here](/slides/04-wrangle2.html)


```{r,echo=FALSE}
xaringanExtra::embed_xaringan(
   url = "/slides/04-wrangle2.html",
   ratio = "16:9"
)
```