---
title: "Causality"
citeproc: true
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-fullnote-bibliography-no-bib.csl
menu: 
  readings:
    parent: Readings
    weight: 7
type: docs
output:
  blogdown::html_page:
    toc: true
editor_options: 
  chunk_output_type: console
---


## Recommended

- [this video from Khan Academy](https://www.khanacademy.org/math/probability/scatterplots-a1/creating-interpreting-scatterplots/v/correlation-and-causality)

- <i class="fas fa-book"></i> [Introduction in Causal Inference: The Mixtape](https://mixtape.scunning.com)^[This reading is mathy-er than what we've covered so far. It also features code from STATA, which we don't use. Don't worry about that so much; we will focus on broad concepts/ideas.]



## Slides

### Tuesday

[Class slides here](/slides/08-causality.html)


```{r,echo=FALSE}
xaringanExtra::embed_xaringan(
   url = "/slides/08-causality.html",
   ratio = "16:9"
)
```


### Thursday

[Class slides here](/slides/08-causality-II.html)


```{r,echo=FALSE}
xaringanExtra::embed_xaringan(
   url = "/slides/08-causality-II.html",
   ratio = "16:9"
)
```