---
title: "Regression discontinuity"
date: "2019-11-12"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

# Slides


[Download slides from today's lecture](/images/slides/20-discontinuity.pdf)


# Example from class


What is incumbency worth?^[example taken from Nick-CH] If you win one election, how likely are you to win a subsequent one? Let's take a regression discontinuity approach to this question. 

Data cleaning steps: 

1. Install and load the `politicaldata` package, and load `data(house_results)`
2. Use `filter` to separate into two new dataframes, one for 2012 and one for 2016
3. For 2012, create new variable (`r_margin`) that tells us the difference in vote share between R and D
4. For 2016, create new variable (`r_wins`) that tells us if R beat D (i.e., vote share of R > vote share of D)
5. In each data set, `select` only `district` and the new variable
6. Use `drop_na` to get rid of missing observations
7. `inner_join` the two resulting datasets


The discontinuity: 

- Think about how to compare the percentage of times `r_wins` just above and below a small threshold in `r_margin` (say, .04)


```{r, eval=FALSE}
# class example
library(tidyverse)
library(politicaldata)
library(socviz)
library(moderndive)
data("house_results")
house_results


# data cleaning
results_2012 = house_results %>% 
  filter(year == 2012) %>% 
  mutate(r_margin = rep - dem) %>% 
  select(district, r_margin) %>% 
  drop_na()

results_2016 = house_results %>% 
  filter(year == 2016) %>% 
  mutate(r_wins = rep > dem) %>%
  select(district, r_wins) %>% 
  drop_na()

# merge them together
full_data = inner_join(results_2012, 
                       results_2016, 
                       by = "district")


# DO THE DISCONTINUITY
discontinuity = full_data %>% 
  filter(abs(r_margin) <= .1) %>% 
  mutate(above = r_margin > 0)

# the estimate:
discontinuity %>% 
  group_by(above) %>% 
  summarise(mean = mean(r_wins))

```

