---
title: Description of assignments
menu:
  assignment:
    parent: Overview
    weight: 1
type: docs
weight: 1
output:
  blogdown::html_page:
    toc: true
---


# Logistics


## Preparation

You will succeed in this class if you (1) attend lecture, (2) attend section, and (3) do the problem sets.



# Assignments


## Weekly check-in

Every week, while you finish working through the content, I want to hear about what you learned and what questions you still have. To do this, you will fill out a short-response on Canvas that simply asks you what (if anything) you: 1) found interesting or compelling from the content so far; 2) found confusing or muddly from the content so far. 



## Problem sets

To practice coding in R you will complete problem sets throughout the quarter. Feel free to work together on the problem sets but **you must turn in your own answers to Canvas.** You cannot work in groups of more than **three** people.


## Coding challenges (**extra credit**)

From time to time, I will hold in-lecture 🔥🔥 **coding challenges** 🔥🔥 that the whole class will participate in. Students will have the opportunity to earn extra credit during these challenges. 


## Final project


You will code -- using all of the tools from the course -- an original data analysis of a mystery dataset. The format will be similar to the homeworks: a take-home RMD file with instructions and empty code chunks for you to fill in. Plus places to write your own analysis. 


## Grade disputes

If you believe that you received the wrong grade on an assignment or exam:

-   send an email specifying **exactly** which questions you believe were graded incorrectly, and provide **specific** justification for why your answer is the correct one. We will then regrade your entire assignment. Your grade may go up, down, or stay the same
-   I will **only accept grade appeals up to three days after the posting of a grade**


### Extensions on assignments (excluding final project)

You can turn in the problem set/weekly check-in one day late, no questions asked, though you will lose a full letter-grade. Beyond that I will not accept late assignments without a doctor's note, so don't ask! The final project will not be accepted late. 

