---
title: "Problem set 5"
date: "2019-10-22"
due_date: "2019-10-22"
due_time: "11:59 PM"
editor_options: 
  chunk_output_type: console
---



## Part I: Making and reading DAGs


We want to estimate the effect of `education` on `earnings`, one of the age-old social science questions. We want to know: does more schooling mean higher lifetime earnings?


 To answer this question, we go all over the US and survey adults about *how many years of education* they completed, their *earnings*, and other characteristics.
 

Draw a DAG that incorporates `education`, `salary`, and the following additional information: 


- `Family wealth`: how wealthy the individual’s parents are
-  `Year of birth`: the year in which they were born
- `School Laws`: whether state has laws requiring people finish high school or not
- `Ability`: imagine people are better at some things than others
-  `Location`: where the person lives and went to school (for simplicity let’s assume everyone went to school in same state where they work)
- `Network connections`: whether or not the individual is well-connected to other people, particularly people who might present job opportunities


### Questions


1. Which variables affect ONLY earnings?  Why don't you think they also affect education?
2. Which variables affect ONLY education? Why don't you think they also affect earnings?
3. Which variables affect BOTH earnings and education?
4. List all the causal paths from *education* to *earnings*. [Feel free to just write: education $\rightarrow$ whatever $\rightarrow$ earnings]
5. Which backdoors do you need to close to identify `education` $\rightarrow$ `salary`? Note: it may not be possible to identify depending on how you drew the DAG (and that's OK!). 



## Part II: Wine and health



Every four and a half minutes there's a new study on [whether or not drinking wine is good for you](https://www.mayoclinic.org/diseases-conditions/heart-disease/in-depth/red-wine/art-20048281). 


Look at the DAG below, where the outcome of interest is `lifespan`. 



```{r echo=FALSE, warning=FALSE, message=FALSE}
library(ggdag)
set.seed(5253240)
dag = dagify(lifespan ~ wine + drugs + health + income, 
       wine ~ health + income, 
       drugs ~ wine,
       health ~ background, 
       income ~ background, 
       exposure = "wine", 
       outcome = "lifespan")
ggdag(dag, text = FALSE, use_labels = "name") + theme_dag_blank()
```



### Questions

1. List all the front-door (direct paths) and back-door (indirect paths) paths from `wine` to `lifespan`
2. What variables would we need to control in order to identify `wine` $\rightarrow$ `lifespan`?


## Part 3: Colliding into a tech company


You work in HR at a tech company where it is your task to a run a survey of the employees. You collect data on various characteristics and find something odd: there's a strong *negative* correlation between how socially skilled an employee is (as measured by some scale) and how technically skilled they are. That is, employees with strong programming skills tend to not be so nice, and those who are very nice tend to not be very good at programming. 


### Questions

1. Discuss how *conditioning on a collider* might explain why you find this odd relationship. 